//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saloon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BeautySalonEntities4 : DbContext
    {
        public BeautySalonEntities4()
            : base("name=BeautySalonEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<client> client { get; set; }
        public virtual DbSet<day_of_week> day_of_week { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<Graphic> Graphic { get; set; }
        public virtual DbSet<history> history { get; set; }
        public virtual DbSet<post> post { get; set; }
        public virtual DbSet<Records> Records { get; set; }
        public virtual DbSet<service> service { get; set; }
        public virtual DbSet<service_list> service_list { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TimeWork> TimeWork { get; set; }
    }
}
