//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saloon
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeWork
    {
        public int id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<int> day_of_week_id { get; set; }
        public Nullable<int> ID_Graphic { get; set; }
    
        public virtual day_of_week day_of_week { get; set; }
        public virtual employee employee { get; set; }
        public virtual Graphic Graphic { get; set; }
    }
}
